#!/bin/bash
BASE_IP="172.16.49."
OUT=""
TEMP=""
RED='\033[0;31m'
NC='\033[0m' # No Color
GREEN='\033[0;32m'
BEGIN="<txt>"
END="</txt>"
ROBS=""
for ID in 1 2 3 4 5
do
 ROBOT_IP="$BASE_IP$ID"

 if timeout 0.3s ping_robot $ROBOT_IP; then
  ROBS=$ROBS"<span weight=\"bold\" fgcolor=\"White\"> | R$ID-></span>""<span weight=\"bold\" fgcolor=\"Green\">ON</span>"
 else
  ROBS=$ROBS"<span weight=\"bold\" fgcolor=\"White\"> | R$ID-></span>""<span weight=\"bold\" fgcolor=\"Red\">OFF</span>"
 fi
done

OUT=""
OUT=$BEGIN$ROBS$END
echo $OUT
