#!/bin/bash
str=$(hostname -I)

if [[ $str != "" ]]; then
   if [[ ${#str} > 15 ]]; then
      if [[ ${#str} < 32 ]]; then
         echo $(hostname -I | cut -d' ' -f2)
      else 
         echo $(hostname -I | cut -d' ' -f1)
      fi
   else 
      echo $(hostname -I | cut -d' ' -f1)
   fi
else 
    echo $(hostname -i)
fi
